name: CI/CD with Docker and GitHub Actions

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t joaopedromendesjava/jptech-catalog:latest .
      
    - name: Log into Docker Hub
      run: docker login -u joaopedromendesjava -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
    - name: Push image to Docker Hub
      run: docker push joaopedromendesjava/jptech-catalog:latest
      
  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_ACCESS_PEM }}
        
    - name: SSH into EC2 instance and update Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-157-130-193.compute-1.amazonaws.com "cd /home/ubuntu && sudo docker stop jptech-catalog-prod && sudo docker rm jptech-catalog-prod && sudo docker rmi joaopedromendesjava/jptech-catalog:v10 && sudo docker pull joaopedromendesjava/jptech-catalog:latest && sudo docker run -p 80:8080 --name jptech-catalog-prod -e APP_PROFILE=prod -e DB_URL=jdbc:postgresql://pgjptech.chcsuyiyuiu7.us-east-1.rds.amazonaws.com:5432/pgjptech -e DB_USERNAME=postgres -e DB_PASSWORD=ADM-sa123 joaopedromendesjava/jptech-catalog:latest"